### PR TITLE
Added dbw_mkz_msgs and updated waypoint_updater

### PR DESCRIPTION
**Pull request by xiaohuieddie**
Currently the vehicle can run in the simulator and follow the waypoints smoothly. The package `dbw_mkz_msgs` was added back so we don't have to install this package every time before running the simulator.

Right now the problem we need to fix is: when the Camera is turned on in the simulator, the car can't be ran properly and will fall off the road. I checked the Knowledge base in Udacity: [https://knowledge.udacity.com/questions/60949](url). Probably need to fine tune the camera image data.

### CODE REVIEW

**Comment by felix-larsen** [comment]
I will take a look at the camera thing tomorrow. I will need to get an overview of all what you have done. But it looks great so far.

**Comment by xiaohuieddie** [comment]
Hi @i4guar 

I think we have already completed most of the required word in the project. But so far I am not confident about the third part (traffic light detection). Since the simulator is not running properly after turning the camera on, I can't really test if my code is truly working or not.

Not sure if you are using downloaded VM or workspace, but it looks like allocating more memory and core processor in VM is worthwhile to try. Also feel free to let me know if you have any trouble to understand the code I committed.

**Comment by felix-larsen** [comment]
#5 only processes every 4th image so it should accelerate the simulator

**Comment by felix-larsen** [comment]
For me it now works in the Udacity workspace environment. The traffic light detection work flawlessly, amazing work!

**Comment by felix-larsen** [comment]
I had the Test_Mode to true, so the camera data was not actually used. It does not work correctly yet when using the image data. We still have some work to do.

**Comment by felix-larsen** [comment]
#7 Definitely solves the issue with the running while camera is on.

**Pull request merged**
